#ifndef ENTITY_TYPES_H
#define ENTITY_TYPES_H

enum ENTITYTYPE {
	NONE_ENTITY			= -1,
	TMESH_ENTITY		= 0,
	TPARTICLE_ENTITY	= 1,
	TCAMERA_ENTITY		= 2,
	TDOME_ENTITY		= 3,
	TLIGHT_ENTITY 		= 4,
	TTEXT_ENTITY		= 5,
	TROOM_ENTITY		= 6
};

#endif