#ifndef EVENT_ENUM_H
#define EVENT_ENUM_H

enum EventType{
	Type_Unknow					= -1,
	Type_Closed 				=  0,
	Type_Resized				=  1,
	Type_LostFocus				=  2,
	Type_GainedFocus			=  3,
	Type_TextEntered			=  4,
	Type_KeyPressed				=  5,
	Type_KeyReleased			=  6,
	Type_MouseWheelScrolled		=  7,
	Type_MouseButtonPressed		=  8,
	Type_MouseButtonReleased	=  9,
	Type_MouseMoved 			= 10,
	Type_MouseEntered			= 11,
	Type_MouseLeft				= 12,
	Type_JoystickButtonPressed	= 13,
	Type_JoystickButtonReleased	= 14,
	Type_JoystickMoved			= 15,
	Type_JoystickConnected		= 16,
	Type_JoystickDisconnected	= 17,
	Type_TouchBegan      	    = 18,
	Type_TouchMoved				= 19,             
	Type_TouchEnded             = 20,
	Type_SensorChanged          = 21
};

enum KeyboardKey{
    Key_Unknown 	=  -1, 
    Key_A 			=   0,        
    Key_B  			=   1,         
    Key_C          	=   2,
    Key_D          	=   3,
    Key_E         	=   4,
    Key_F          	=   5,
    Key_G           =   6, 
    Key_H           =   7,
    Key_I           =   8,
    Key_J           =   9,
    Key_K           =  10,
    Key_L           =  11,
    Key_M           =  12,
    Key_N           =  13,
    Key_O           =  14,
    Key_P           =  15,
    Key_Q           =  16,
    Key_R           =  17,
    Key_S           =  18,
    Key_T           =  19,
    Key_U           =  20,
    Key_V           =  21,
    Key_W           =  22,
    Key_X           =  23,
    Key_Y           =  24,
    Key_Z           =  25,
    Key_Num0        =  26,
    Key_Num1        =  27,
    Key_Num2        =  28,
    Key_Num3        =  29,
    Key_Num4        =  30,
    Key_Num5        =  31,
    Key_Num6        =  32,
    Key_Num7        =  33,
    Key_Num8        =  34,
    Key_Num9        =  35,
    Key_Escape      =  36,
    Key_LControl    =  37,
    Key_LShift      =  38,
    Key_LAlt      	=  39,
    Key_LSystem    	=  40,
    Key_RControl    =  41,
    Key_RShift     	=  42,
    Key_RAlt       	=  43,
    Key_RSystem     =  44,
    Key_Menu        =  45,
    Key_LBracket   	=  46,
    Key_RBracket  	=  47,
    Key_SemiColon 	=  48,
    Key_Comma    	=  49,
    Key_Period    	=  50,
    Key_Quote    	=  51,
    Key_Slash     	=  52,
    Key_BackSlash 	=  53,
    Key_Tilde     	=  54,
    Key_Equal   	=  55,
    Key_Dash    	=  56,
    Key_Space      	=  57,
    Key_Return   	=  58,
    Key_BackSpace	=  59,
    Key_Tab        	=  60,
    Key_PageUp   	=  61,
    Key_PageDown   	=  62,
    Key_End      	=  63,
    Key_Home       	=  64,
    Key_Insert 		=  65,
    Key_Delete    	=  66,
    Key_Add     	=  67,
    Key_Subtract  	=  68,
    Key_Multiply 	=  69,
    Key_Divide     	=  70,
    Key_Left       	=  71,
    Key_Right    	=  72,
    Key_Up         	=  73,
    Key_Down       	=  74,
    Key_Numpad0   	=  75,
    Key_Numpad1  	=  76,
    Key_Numpad2   	=  77,
    Key_Numpad3    	=  78,
    Key_Numpad4  	=  79,
    Key_Numpad5  	=  80,
    Key_Numpad6    	=  81,
    Key_Numpad7   	=  82,
    Key_Numpad8    	=  83,
    Key_Numpad9    	=  84,
    Key_F1         	=  85,
    Key_F2          =  86,
    Key_F3          =  87,
    Key_F4          =  88,
    Key_F5          =  89,
    Key_F6          =  90,
    Key_F7          =  91,
    Key_F8          =  92,
    Key_F9          =  93,
    Key_F10         =  94,
    Key_F11         =  95,
    Key_F12         =  96,
    Key_F13         =  97,
    Key_F14         =  98,
    Key_F15         =  99,
    Key_Pause		= 100,

    Key_KeyCount	= 101
};

enum ButtonMouse{
	ButtonMouse_Unknown 	= -1,
    ButtonMouse_Left 		=  0,       
    ButtonMouse_Right 		=  1,      
    ButtonMouse_Middle 		=  2,     
    ButtonMouse_XButton1 	=  3,   
    ButtonMouse_XButton2	=  4,   
    ButtonMouse_ButtonCount	=  5 
};

enum JoystickAxis{
    X 		= 0,    
    Y 		= 1,    
    Z 		= 2,    
    R 		= 3,    
    U 		= 4,    
    V 		= 5,    
    PovX	= 6, 
    PovY	= 7  
};

enum SensorType{
    Accelerometer 		= 0,    
    Gyroscope 			= 1,        
    Magnetometer    	= 2,     
    Gravity 			= 3,          
    UserAcceleration	= 4, 
    Orientation			= 5,      
    Count             	= 6
};

#endif